variables:
  GIT_DEPTH: 10
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

stages:
  - test
  - score

test-code-vm:
  stage: test
  script:
    - pub run test

test-code-node:
  stage: test
  script:
    - "export $PATH:/usr/lib/dart/bin$HOME/.pub-cache/bin \
    pub run test -p node"

test-code-chrome:
  stage: test
  script:
    - "export $PATH:/usr/lib/dart/bin:$HOME/.pub-cache/bin \
    pub run test -p chrome"

score-pana:
  stage: score
  script:
    - "export $PATH:/usr/lib/dart/bin:$HOME/.pub-cache/bin \
    pub global activate pana \
    pana ."
